version: '3.8'

services:
  analytics:
    build: .
    ports:
      - '8000:8000'
    environment:
      - APP_ENV=production
      - POSTGRES_HOST=analytics-db
    depends_on:
      - analytics-db

  analytics-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=analytics_user
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=timelycapsule_analytics
    volumes:
      - analytics-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  analytics-data:
